oauth:
    user:
      clientId: clientOne
      clientSecret: clientsecret

    tokenValidityInSeconds: 3600
    refreshTokenValidityInSeconds: 86400

security:
    username: username
    password: password



